packages:
    - packages/*

allowBuilds:
    core-js: true
    unrs-resolver: true

catalog:
    "@types/node": ^24.13.2
    prettier: ^3.8.4

minimumReleaseAgeExclude:
    - "@1adybug/xlsx"
    - deepsea-tools
    - deepsea-components
    - soda-hooks
